# fly.toml app configuration file generated for uni-cycle-cold-wave-3543 on 2025-08-02T16:30:57+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uni-cycle-cold-wave-3543'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"

# Removed legacy [services] section to avoid conflicting health checks.
